time:
  enable: true
  year: 2023
  month: 8
  date: 27
  hour: 12
dream:
  title: 自由！民主！
  text: 为践行宪法赋予我等无上的权利，吾辈应尽到一个中国公民的社会责任，为索取我们那本该拥有的权利而不懈奋斗！
music:
  enable: false
reward:
  enable: false
socialLink:
  github: https://github.com/zhengxyz123
  email: 3422794023@qq.com
  qq: 3422794023
  rss: false
mathjax:
  enable: true
profile:
  career: 自由の开发者
  introduction: 人生如梦，一尊还酹江月
myProjects:
  enable: true
  data:
    Minecraftpy:
      icon: fas fa-file-alt
      iconBackground: 'linear-gradient(to bottom right, #66BB6A 0%, #81C784 100%)'
      url: https://github.com/minecraft-py/minecraft
      desc: 一款类Minecraft的游戏
mySkills:
  enable: true
  data:
    Python:
      background: 'linear-gradient(to right, #FF0066 0%, #FF00CC 100%)'
      percent: 85%
indexbtn:
  url: https://github.com/zhengxyz123
githubLink:
  url: https://github.com/zhengxyz123/zhengxyz123.github.io
subtitle:
  enable: false
translate:
  enable: true
